version: '3.8'

services:
  db-collector:
    build: .
    container_name: db-collector
    restart: unless-stopped
    ports:
      - "42000:42000"
    environment:
      - BT_CLIENT_SECRET=${BT_CLIENT_SECRET}
      - BT_CLIENT_ID=${BT_CLIENT_ID}
      - BT_API_URL=${BT_API_URL}
      - LOCAL_PASS=${LOCAL_PASS}
      - LOCAL_USER="${LOCAL_USER}"
      # Define o fuso horário para os logs e intervalos de query
      - TZ=America/Sao_Paulo
    volumes:
      # MAPEAMENTO DE VOLUME:
      # Isso permite que você edite os YAMLs na sua máquina e o container 
      # leia as mudanças sem precisar de um novo "docker build".
      - ./config:/root/config:ro
    networks:
      - monitoramento_network

networks:
  monitoramento_network:
    driver: bridge