app_configs:
  databases_dir: "config"
  commands_dir: "commands"
  wait_kollector_metrics_update: 120
  wait_disconnected_sessions_reconnect: 50

run_configs:

  - name: 'off'
    wait_seconds: -1
    only_run_on_dbtype: []
    only_run_on_area: []
    only_run_on_db: []

  - name: 'asm'
    wait_seconds: 60
    only_run_on_dbtype: ['oracle']
    only_run_on_area: ['any']
    only_run_on_db: ['TESTE']

  - name: 'slow'
    wait_seconds: 1800
    only_run_on_dbtype: ['oracle']
    only_run_on_area: ['any']
    only_run_on_db: ['any']

  - name: 'slow-12h'
    wait_seconds: 1800
    only_run_on_dbtype: ['oracle']
    only_run_on_area: ['any']
    only_run_on_db: ['any']

  - name: 'normal'
    wait_seconds: 360
    only_run_on_dbtype: ['oracle']
    only_run_on_area: ['any']
    only_run_on_db: ['any']

  - name: 'normal-1h'
    wait_seconds: 3600
    only_run_on_dbtype: ['oracle']
    only_run_on_area: ['any']
    only_run_on_db: ['any']