server_port: "42000"
log_level: "info"

auth:
  method: "beyondtrust"
  cache_ttl: "30m"
  beyondtrust:
    api_url: "${BT_API_URL}"
    client_id: "${BT_CLIENT_ID}"
    client_secret: "${BT_CLIENT_SECRET}"
  local_credentials:
    - id: "acesso_manual_dev"
      user: "${LOCAL_USER}"
      pass: "${LOCAL_PASS}"