dbs:

  - name: 'TESTE'
    user: 'USUARIO'
    btsys_name: 'teste-dbnonproduction (Db Instance: TESTE, Port:1521)'
    btacc_name: 'USUARIO'
    dbType: 'oracle'
    IsCdb: false
    Area: 'PRD'
    targets:
      - 'localhost'
